#!/bin/bash

################################################################################
## Convert syntax into LaTeX hyperlinks.
## 
## Usage:
## classref <name> [<levels>]
##
## Example: $ classref BiometricEvaluation::IO::RecordStore
##  Output: > \hyperlink{class_biometric_evaluation_1_1_i_o_1_1_record_store}\
##            {RecordStore}
##
## Example: $ classref BiometricEvaluation::IO::RecordStore 2
##  Output: > \hyperlink{class_biometric_evaluation_1_1_i_o_1_1_record_store}\
##            {IO::RecordStore}
################################################################################

input=$1

### Use the prefix of the executible name as the type we're substituting so
### that there is only one source for each type (namespace, class, etc.).
exeName=`basename $0`
prefix=`echo $exeName | sed 's/\(.*\)doxyref/\1/'`

### Generate the label
label=$input
# Underscore capital letters
label=`echo $label | sed 's/\([A-Z]\)/_\1/g'`
# Replace namespace delimiters
label=`echo $label | sed 's/:/_1/g'`
# Lowercase everything
label=`echo $label | tr [A-Z] [a-z]`

### Generate the caption
if [ $# -eq 2 ]; then
	# Use $2 namespaces (including class name) for caption
	caption=`echo $input | awk \
	'BEGIN{FS="::"}{for (i = NF + 1 - '$2'; i <= NF; i++) {{printf "%s", $i}; if ($i != $NF) { printf "::" }}}'`
else
	caption=`echo $input | awk 'BEGIN{FS="::"}{printf "%s", $NF}'`
fi
### Allow linebreaks in caption where appropriate
# Lowercase letter before uppercase letter
caption=`echo $caption | sed 's/\([a-z]\)\([A-Z]\)/\1\\\allowbreak \2/g'`
# Namespace delimiter
caption=`echo $caption | sed 's/\(::\)/\\\allowbreak \1\\\allowbreak /g'`

echo -n "\hyperlink{${prefix}${label}}{\\${prefix}{$caption}}"
